"""Generate Markdown reports from audit results."""

from datetime import datetime


def generate_markdown_report(results):
    """Generate a Markdown-formatted GEO audit report."""
    url = results["url"]
    score = results["score"]
    grade = results.get("grade", "")
    audits = results["audits"]
    timestamp = results.get("timestamp", datetime.utcnow().isoformat())

    lines = [
        f"# GEO Audit Report",
        f"",
        f"**URL:** {url}  ",
        f"**Date:** {timestamp}  ",
        f"**AI Citability Score:** {score}/100 (Grade: {grade})",
        f"",
        f"---",
        f"",
    ]

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Check | Status | Score |")
    lines.append("|-------|--------|-------|")

    for audit in audits:
        status = "PASS" if audit.get("passed") else "WARN" if audit.get("warning") else "FAIL"
        emoji = {"PASS": "✅", "WARN": "⚠️", "FAIL": "❌"}.get(status, "")
        lines.append(f"| {audit['name']} | {emoji} {status} | {audit.get('score', 0)}/100 |")

    lines.append("")

    # Detailed results
    lines.append("## Detailed Results")
    lines.append("")

    for audit in audits:
        status = "PASS" if audit.get("passed") else "WARN" if audit.get("warning") else "FAIL"
        lines.append(f"### {audit['name']} — {status}")
        lines.append("")
        lines.append(audit["description"])
        lines.append("")

        if audit.get("details"):
            for detail in audit["details"]:
                lines.append(f"- {detail}")
            lines.append("")

        if audit.get("recommendation"):
            lines.append(f"**Recommendation:** {audit['recommendation']}")
            lines.append("")

    # Footer
    passed = sum(1 for a in audits if a.get("passed"))
    warned = sum(1 for a in audits if a.get("warning"))
    failed = sum(1 for a in audits if not a.get("passed") and not a.get("warning"))

    lines.append("---")
    lines.append("")
    lines.append(f"**{passed} passed** | **{warned} warnings** | **{failed} failed**")
    lines.append("")
    lines.append("*Generated by [geo-toolkit](https://github.com/infinitelabsdigital/geo-toolkit)*")

    return "\n".join(lines)
